log_food:
  name: Log Food
  description: Log a food entry for a user.
  fields:
    spoken_name:
      name: Spoken Name
      example: "Eleanor"
      required: true
      selector:
        text:
    food_item:
      name: Food Item
      example: "White Chocolate Shrimp"
      required: true
      selector:
        text:
    calories:
      name: Calories
      example: 250
      required: true
      selector:
        number:
          min: 0
          max: 4000
          step: 10
    timestamp:
      name: Timestamp
      example: "2025-08-04T14:30"
      selector:
        text:

log_exercise:
  name: Log Exercise
  description: Log an exercise entry for a user.
  fields:
    spoken_name:
      name: Spoken Name
      example: "Chidi"
      required: true
      selector:
        text:
    exercise_type:
      name: Exercise Type
      example: "Stomach Clenches"
      required: true
      selector:
        text:
    duration:
      name: Duration
      example: 30
      selector:
        number:
          min: 0
          max: 600
          step: 1
    calories_burned:
      name: Calories Burned
      example: 500
      required: true
      selector:
        number:
          min: 0
          max: 4000
          step: 10
    timestamp:
      name: Timestamp
      example: "2025-08-04T14:30"
      selector:
        text:

log_weight:
  name: Log Weight
  description: Log a weight entry for a user.
  fields:
    spoken_name:
      name: Spoken Name
      example: "Tahani"
      required: true
      selector:
        text:
    weight:
      name: Weight
      example: 120.5
      required: true
      selector:
        number:
          min: 0
          max: 1000
          step: 0.1
    timestamp:
      name: Timestamp
      example: "2025-08-04"
      selector:
        text:

log_body_fat:
  name: Log Body Fat
  description: Log a body fat percentage entry for a user.
  fields:
    spoken_name:
      name: Spoken Name
      example: "Glenn"
      required: true
      selector:
        text:
    body_fat_pct:
      name: Body Fat Percentage
      example: 35.0
      required: true
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
    timestamp:
      name: Timestamp
      example: "2025-08-04"
      selector:
        text:

fetch_data:
  name: Fetch Data
  description: Fetch all entries (food, exercise, weight, body fat, BMR) for a user on a given day.
  fields:
    spoken_name:
      name: Spoken Name
      example: "Doug"
      required: true
      selector:
        text:
    timestamp:
      name: Date
      example: "2025-08-04"
      description: Date in YYYY-MM-DD format. If not provided, defaults to today.
      selector:
        text: